name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: Update-versions
        run: pnpm run update-versions

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/userscripts

      - name: Git config
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false

      - name: Check changes
        id: check
        run: |
          changed=$(git diff --name-only remotes/origin/master..remotes/origin/releases -- userscripts)
          if [ -n "$changed" ]; then  
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit versions-update
        if: steps.check.outputs.has_changes == 'true'
        run: |
          git add userscripts
          git commit -m "Update versions"

      - name: Push to ref
        if: steps.check.outputs.has_changes == 'true'
        run: |
          git push origin HEAD:${{ github.ref_name }}
