name: Build and Release

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: pnpm run build
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Configure Git
      run: | 
        git config --global user.name '${{ secrets.GIT_USERNAME }}'
        git config --global user.email '${{ secrets.GIT_EMAIL }}'

    - name: Commit releases
      run: |
        git add -f dist
        git commit -m "releases"

    - name: Push to releases
      run: |
        git push origin HEAD:releases